"""
Seed Pre-Planned Activities for Bhopal Division (P.Way, TRD, S&T)
Preserves the existing 50 blocks and 64 tasks.
Adds distinct planned activities categorized as:
1. CURRENT / TODAY (DUE NOW)
2. WEEKLY
3. MONTHLY
"""

import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from backend.app.database import SessionLocal, engine, Base
from backend.app.models.maintenance import PlannedActivity

def seed_planned_activities():
    # Ensure table exists
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        existing_count = db.query(PlannedActivity).count()
        if existing_count > 0:
            print(f"Planned activities already populated ({existing_count} records). Skipping.")
            return

        activities = [
            # ==========================================
            # 1. CURRENT / TODAY (DUE NOW - 2026-09-25)
            # ==========================================
            PlannedActivity(
                id="ACT-TRD-CUR-01",
                department_id="TRD",
                title="OHE Inspection — BNI–NDPM",
                cadence="CURRENT",
                scheduled_date="2026-09-25",
                start_time="20:00",
                end_time="22:00",
                duration_mins=120,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-NDPM-BNI",
                location_km=58.40,
                location_description="Budhni (BNI) — Narmadapuram (NDPM)",
                track_name="DOWN_MAIN",
                assigned_crew="OHE Inspection Gang #2",
                priority="CRITICAL",
                status="DUE_NOW",
                description="Live contact wire stagger and height calibration along Narmada bridge approaches.",
            ),
            PlannedActivity(
                id="ACT-PWAY-CUR-01",
                department_id="PWAY",
                title="Track Inspection & Creep Measurement — ET–PRKD",
                cadence="CURRENT",
                scheduled_date="2026-09-25",
                start_time="20:30",
                end_time="22:30",
                duration_mins=120,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-ET-PRKD",
                location_km=14.20,
                location_description="Itarsi (ET) — Powarkheda (PRKD)",
                track_name="UP_MAIN",
                assigned_crew="Track Maintenance Gang #4",
                priority="HIGH",
                status="DUE_NOW",
                description="Long welded rail (LWR) thermal de-stressing audit and longitudinal creep measurement.",
            ),
            PlannedActivity(
                id="ACT-SNT-CUR-01",
                department_id="SNT",
                title="Point Machine & Axle Counter Testing — BPL Yard",
                cadence="CURRENT",
                scheduled_date="2026-09-25",
                start_time="21:00",
                end_time="23:00",
                duration_mins=120,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-RKMP-BPL",
                location_km=824.50,
                location_description="Bhopal Junction Yard (BPL)",
                track_name="DOWN_MAIN",
                assigned_crew="S&T Electronic Interlocking Team",
                priority="HIGH",
                status="DUE_NOW",
                description="Routine night testing of dual-detection digital axle counter (DAC) heads and turnout 104.",
            ),

            # ==========================================
            # 2. WEEKLY ACTIVITIES (Sep 25 – Oct 01)
            # ==========================================
            PlannedActivity(
                id="ACT-TRD-WKL-01",
                department_id="TRD",
                title="25 Sep — OHE Catenary Height & Stagger Verification",
                cadence="WEEKLY",
                scheduled_date="2026-09-25",
                start_time="14:00",
                end_time="16:00",
                duration_mins=120,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-NDPM-BNI",
                location_km=42.00,
                location_description="Hoshangabad Ghat Section",
                track_name="UP_MAIN",
                assigned_crew="OHE Tower Wagon Squad #1",
                priority="P2",
                status="SCHEDULED",
                description="Scheduled weekly measurement of contact wire wear and dropper verticality.",
            ),
            PlannedActivity(
                id="ACT-TRD-WKL-02",
                department_id="TRD",
                title="27 Sep — Substation Transformer Bushing Inspection",
                cadence="WEEKLY",
                scheduled_date="2026-09-27",
                start_time="10:00",
                end_time="12:30",
                duration_mins=150,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-BHS-BINA",
                location_km=68.20,
                location_description="Vidisha Traction Substation",
                track_name="DOWN_MAIN",
                assigned_crew="Traction Power Substation Squad",
                priority="P2",
                status="SCHEDULED",
                description="Thermal imaging of 132/25kV traction transformer bushings and circuit breaker gas pressure check.",
            ),
            PlannedActivity(
                id="ACT-TRD-WKL-03",
                department_id="TRD",
                title="29 Sep — Neutral Section Overhaul & Isolator Check",
                cadence="WEEKLY",
                scheduled_date="2026-09-29",
                start_time="11:00",
                end_time="13:00",
                duration_mins=120,
                corridor_id="CORR-02",
                section_id="SEC-CORR-02-KNW-HD",
                location_km=112.50,
                location_description="Harda Outer Neutral Section",
                track_name="UP_MAIN",
                assigned_crew="OHE Maintenance Squad #3",
                priority="P3",
                status="SCHEDULED",
                description="Inspection of PTFE short neutral section rod assembly and motorized isolator contacts.",
            ),
            PlannedActivity(
                id="ACT-PWAY-WKL-01",
                department_id="PWAY",
                title="26 Sep — Track Tamping & Alignment Check — Mandideep",
                cadence="WEEKLY",
                scheduled_date="2026-09-26",
                start_time="09:00",
                end_time="11:30",
                duration_mins=150,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-MDDP-RKMP",
                location_km=72.30,
                location_description="Mandideep Industrial Siding Junction",
                track_name="DOWN_MAIN",
                assigned_crew="P.Way Tamping Crew #1",
                priority="P2",
                status="SCHEDULED",
                description="Mechanized tamping using CSM-09 machine with pre-tamping lifting and lining audit.",
            ),
            PlannedActivity(
                id="ACT-PWAY-WKL-02",
                department_id="PWAY",
                title="27 Sep — Track inspection & Rail Thermit Weld Testing",
                cadence="WEEKLY",
                scheduled_date="2026-09-27",
                start_time="08:00",
                end_time="10:00",
                duration_mins=120,
                corridor_id="CORR-03",
                section_id="SEC-CORR-03-BINA-GUNA",
                location_km=38.60,
                location_description="Mungaoli Section",
                track_name="SINGLE_LINE",
                assigned_crew="USFD Inspection Gang #2",
                priority="P2",
                status="SCHEDULED",
                description="Visual and dye penetrant inspection of flash butt and AT welds across bridge approaches.",
            ),
            PlannedActivity(
                id="ACT-PWAY-WKL-03",
                department_id="PWAY",
                title="30 Sep — Curve Check & Ballast Profiling — Hoshangabad",
                cadence="WEEKLY",
                scheduled_date="2026-09-30",
                start_time="13:00",
                end_time="15:00",
                duration_mins=120,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-NDPM-BNI",
                location_km=18.90,
                location_description="Curve No. 4 near Hoshangabad",
                track_name="DOWN_MAIN",
                assigned_crew="Track Maintenance Gang #2",
                priority="P3",
                status="SCHEDULED",
                description="Superelevation and cant deficiency check on transition curve; shoulder ballast replenishment.",
            ),
            PlannedActivity(
                id="ACT-SNT-WKL-01",
                department_id="SNT",
                title="26 Sep — Track Circuit Joint Insulation Testing — Bina",
                cadence="WEEKLY",
                scheduled_date="2026-09-26",
                start_time="10:30",
                end_time="12:30",
                duration_mins=120,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-BHS-BINA",
                location_km=140.20,
                location_description="Bina Junction South Cabin",
                track_name="UP_MAIN",
                assigned_crew="S&T Maintenance Gang #1",
                priority="P2",
                status="SCHEDULED",
                description="Testing insulation resistance of glued joints and impedance bonds for DC track circuits.",
            ),
            PlannedActivity(
                id="ACT-SNT-WKL-02",
                department_id="SNT",
                title="28 Sep — Signal Lamp & LED Aspect Intensity Calibration",
                cadence="WEEKLY",
                scheduled_date="2026-09-28",
                start_time="14:00",
                end_time="16:00",
                duration_mins=120,
                corridor_id="CORR-04",
                section_id="SEC-CORR-04-GUNA-GWL",
                location_km=85.00,
                location_description="Shivpuri Station Outer",
                track_name="DOWN_MAIN",
                assigned_crew="S&T Signal Gang #3",
                priority="P3",
                status="SCHEDULED",
                description="Photometric lux testing of red, yellow, green LED signal aspect units and current regulators.",
            ),
            PlannedActivity(
                id="ACT-SNT-WKL-03",
                department_id="SNT",
                title="29 Sep — S&T Equipment Inspection & Interlocking Test",
                cadence="WEEKLY",
                scheduled_date="2026-09-29",
                start_time="09:30",
                end_time="12:00",
                duration_mins=150,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-NDPM-BNI",
                location_km=55.10,
                location_description="Budhni Interlocking Cabin",
                track_name="DOWN_MAIN",
                assigned_crew="S&T Electronic Interlocking Squad",
                priority="P2",
                status="SCHEDULED",
                description="Square lock, detector slide clearance test and route initiation interlock timing audit.",
            ),

            # ==========================================
            # 3. MONTHLY ACTIVITIES (Late Sep – Oct)
            # ==========================================
            PlannedActivity(
                id="ACT-TRD-MON-01",
                department_id="TRD",
                title="28 Sep — TRD Preventive Inspection & Contact Wire Wear Check",
                cadence="MONTHLY",
                scheduled_date="2026-09-28",
                start_time="10:00",
                end_time="13:00",
                duration_mins=180,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-ET-PRKD",
                location_km=32.50,
                location_description="Powarkheda — Hoshangabad Section",
                track_name="UP_MAIN",
                assigned_crew="TRD Divisional Inspection Team",
                priority="P2",
                status="SCHEDULED",
                description="Comprehensive monthly micrometer audit of copper contact wire residual thickness along main line.",
            ),
            PlannedActivity(
                id="ACT-TRD-MON-02",
                department_id="TRD",
                title="06 Oct — High-Voltage Insulator Washing & Anti-Pollution Cleaning",
                cadence="MONTHLY",
                scheduled_date="2026-10-06",
                start_time="08:30",
                end_time="11:30",
                duration_mins=180,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-MDDP-RKMP",
                location_km=92.40,
                location_description="Mandideep Industrial Sector",
                track_name="DOWN_MAIN",
                assigned_crew="TRD Washing & Maintenance Squad",
                priority="P3",
                status="SCHEDULED",
                description="High-pressure de-mineralized water jet washing of 25kV stay and bracket insulators.",
            ),
            PlannedActivity(
                id="ACT-TRD-MON-03",
                department_id="TRD",
                title="14 Oct — OHE Foundation & Mast Integrity Audit",
                cadence="MONTHLY",
                scheduled_date="2026-10-14",
                start_time="11:00",
                end_time="13:30",
                duration_mins=150,
                corridor_id="CORR-02",
                section_id="SEC-CORR-02-KNW-HD",
                location_km=148.00,
                location_description="Khandwa Outer Embankment",
                track_name="DOWN_MAIN",
                assigned_crew="TRD Civil & Structural Gang",
                priority="P3",
                status="SCHEDULED",
                description="Ultrasonic concrete foundation core testing and mast plumb alignment verification.",
            ),
            PlannedActivity(
                id="ACT-PWAY-MON-01",
                department_id="PWAY",
                title="02 Oct — Ultrasonic Flaw Detection (USFD) Rail Testing",
                cadence="MONTHLY",
                scheduled_date="2026-10-02",
                start_time="08:00",
                end_time="12:00",
                duration_mins=240,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-NDPM-BNI",
                location_km=62.00,
                location_description="Midghat Mountain Pass",
                track_name="UP_MAIN",
                assigned_crew="USFD Specialized Testing Team #1",
                priority="CRITICAL",
                status="SCHEDULED",
                description="Continuous USFD trolley scan for internal gauge face fatigue defects and transverse fissures.",
            ),
            PlannedActivity(
                id="ACT-PWAY-MON-02",
                department_id="PWAY",
                title="05 Oct — P.Way Scheduled Inspection & Switch Expansion Joint Service",
                cadence="MONTHLY",
                scheduled_date="2026-10-05",
                start_time="09:00",
                end_time="11:00",
                duration_mins=120,
                corridor_id="CORR-03",
                section_id="SEC-CORR-03-BINA-GUNA",
                location_km=45.70,
                location_description="Ashoknagar Section",
                track_name="SINGLE_LINE",
                assigned_crew="Track Maintenance Gang #5",
                priority="P2",
                status="SCHEDULED",
                description="SEJ gap measurement under thermal expansion range; lubrication of stock and switch rails.",
            ),
            PlannedActivity(
                id="ACT-PWAY-MON-03",
                department_id="PWAY",
                title="15 Oct — Deep Screening & Ballast Cleaning Machine (BCM) Run",
                cadence="MONTHLY",
                scheduled_date="2026-10-15",
                start_time="07:30",
                end_time="11:30",
                duration_mins=240,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-BHS-BINA",
                location_km=118.20,
                location_description="Ganj Basoda — Bina Section",
                track_name="DOWN_MAIN",
                assigned_crew="Heavy Track Machine (BCM) Crew",
                priority="HIGH",
                status="SCHEDULED",
                description="Full-depth ballast screening and muck evacuation to restore track elasticity and drainage.",
            ),
            PlannedActivity(
                id="ACT-SNT-MON-01",
                department_id="SNT",
                title="04 Oct — Electronic Interlocking (EI) Diagnostic & Standby System Check",
                cadence="MONTHLY",
                scheduled_date="2026-10-04",
                start_time="10:00",
                end_time="12:30",
                duration_mins=150,
                corridor_id="CORR-01",
                section_id="SEC-CORR-01-MDDP-RKMP",
                location_km=80.50,
                location_description="Rani Kamalapati (RKMP) Relay Room",
                track_name="DOWN_MAIN",
                assigned_crew="S&T Senior Systems Engineer Cell",
                priority="HIGH",
                status="SCHEDULED",
                description="Warm standby changeover test, vital CPU checksum verification, and surge arrestor health check.",
            ),
            PlannedActivity(
                id="ACT-SNT-MON-02",
                department_id="SNT",
                title="12 Oct — S&T Equipment Maintenance & Point Machine Motor Overhaul",
                cadence="MONTHLY",
                scheduled_date="2026-10-12",
                start_time="09:00",
                end_time="11:30",
                duration_mins=150,
                corridor_id="CORR-04",
                section_id="SEC-CORR-04-GUNA-GWL",
                location_km=104.00,
                location_description="Gwalior South Approach Yard",
                track_name="UP_MAIN",
                assigned_crew="Point Maintenance Gang #2",
                priority="P2",
                status="SCHEDULED",
                description="Motor carbon brush replacement, friction clutch slipping current calibration and gear box oil flush.",
            ),
            PlannedActivity(
                id="ACT-SNT-MON-03",
                department_id="SNT",
                title="18 Oct — Audio Frequency Track Circuit (AFTC) Tuning & Calibration",
                cadence="MONTHLY",
                scheduled_date="2026-10-18",
                start_time="14:00",
                end_time="16:30",
                duration_mins=150,
                corridor_id="CORR-02",
                section_id="SEC-CORR-02-KNW-HD",
                location_km=76.80,
                location_description="Khirkiya — Harda Section",
                track_name="UP_MAIN",
                assigned_crew="AFTC Electronics Specialist Squad",
                priority="P3",
                status="SCHEDULED",
                description="End-to-end frequency response tuning (1.7kHz / 2.3kHz) and bond impedance calibration under wet conditions.",
            ),
        ]

        db.add_all(activities)
        db.commit()
        print(f"Successfully seeded {len(activities)} planned activities (Current, Weekly, Monthly) across PWAY, TRD, and SNT.")
    finally:
        db.close()

if __name__ == "__main__":
    seed_planned_activities()
